server:
  port: 8081

spring:
  application:
    name: GatewayApplication

  cloud:
    gateway:
      routes:
        - id: LearningSystemApplication
          uri: http://localhost:8080/
          predicates:
            - Path=/lms/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
